# syntax=docker/dockerfile:1
FROM golang:1.24-alpine

WORKDIR /app

# Install Air for live-reloading
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Expose the default port for the app
EXPOSE 3000

# Use Air to run the application
CMD ["air"]
